### ISSUE TITLE
Landing page body

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#118]
body of the landing page

**Comment by thatsamedolapo** [comment]
I worked on the About us page,what are favicons, how to use favicons and provided some images.My team mates added more spice to it and made it much better. We ensure we made good use of our style guide and spacing system.

**Comment by Sinonaif** [comment]
built the flow/architecture for the body, combined all frames with different content into one piece, which is the beautiful landing page displayed

**Comment by neniio** [comment]
I worked with team mate (matacheee) to share ideas of how the body of the landing page should be designed and structured. A wireframe was created in that regards. Whilst my other team mates assigned to the task carried out the designs.

**Comment by joanamadasun** [comment]
I contributed to the creative process along with the general team members during the creation of the landing page 

I created the icon images
https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=2835%3A4431 

and this modal  https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=2069%3A2846
