### ISSUE TITLE
Design system

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#119]
This task was to create the backbone of the entire designs, which one of the most tedious and but these guys handled it with professionalism.

**Comment by nwokomacj** [comment]
It was a good team work with Joan, working on the style guide for the project.
Of a truth, style guide is the structure of every design

**Comment by Sinonaif** [comment]
I updated(made few additions) to the colour and text style in the design system

**Comment by joanamadasun** [comment]
i created the button material design
[https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=206%3A11333](url)

Colour style [https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=751%3A1411](url)

input fields material design[https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=1638%3A1923](url)

spacing system [https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=766%3A683](url)

Text styles[https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=963%3A1093](url)

Text colour style [https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=1335%3A1852](url)

Borders, lines and dividers [https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=1488%3A1741](url)

shadow style- blue umbra, blue penumbra, blue ambient [https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=766%3A745](url)

Dropdown components [https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=800%3A563](url)

**Comment by nwokomacj** [comment]
grid layout for desktop view
 https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=1752%3A2520
grid layout for mobile view
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=952%3A867
shadow styles: 24dp umbra, 24dp penumbra, 24dp ambient
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=766%3A745
button variants: primary, secondary, borders, components, autolayout
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=206%3A11333
input fields, check boxes
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=1638%3A1923
