### ISSUE TITLE
Edit profile page

### ISSUE THREAD

**Issue by Jay-davisphem** [zuri-training/Favicon_gen-Team-68#12]
Creating the Edit profile page for both mobile and desktop views

Note: dont forget to use the style guide and observe the 4 point system

submission date: 6pm friday (7/29/2022)

**Comment by nwokomacj** [comment]
I worked on the profile page with a team member for both desktop and mobile views taken into consideration our style guide and spacing system.

**Comment by thatsamedolapo** [comment]
I worked with a team mate and we made sure we made use of our spacing system and style guide in making the edit profile page

**Comment by Sinonaif** [comment]
Did some adjustments to the already created designs, which was to make it a modal and not a full page

**Comment by nwokomacj** [comment]
I worked with @thatsamedolapo to design the edit profile page both desktop and mobile view. However, the team leader also added in his contribution
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=2979%3A9500
