### ISSUE TITLE
Landing page footer

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#120]
mobile and desktop footer designs of the landing page

**Comment by thatsamedolapo** [comment]
We brainstormed on what we are to add to our footer putting into consideration our style guide and spacing system .

**Comment by Sinonaif** [comment]
brought several templates and worked on the desktop footer with @thatsamedolapo and we shaped the footer.

**Comment by Adevikthur** [comment]
Arranged the footer assets to align with the spacing system and visual hierarchy
https://www.figma.com/file/Om0i0dm6XOQN27utcHw5QD/Team-68_Conficon?node-id=2956%3A5817
