### ISSUE TITLE
Hero section of landing page

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#121]
the whole team participated in the making of the hero setion

**Comment by nwokomacj** [comment]
It was a wonderful experience working with this team.

**Comment by thatsamedolapo** [comment]
It was a nice experience and I learnt a lot from my team mates and vice versa.

**Comment by Macdonald37** [comment]
The team had contributions in this particular process. It was enlightening as I experienced first hand the intelligent thought process of the team.

**Comment by Sinonaif** [comment]
This part was collaborative, that means the whole team had a say the look of the hero section. I brought several templates to easy the decision making process, and also made valuable contributions that shaped the structure of the hero section.

**Comment by neniio** [comment]
The hero section was basically our first hi-fi design and pretty everybody shared creative ideas. I contributed in the process.

**Comment by asamstudios** [comment]
In our first design right off the bat, I had a little bit of an issue syncing with the team at first(network problem) but I was able to make contributions and adjustments to Hero Section.

**Comment by Adevikthur** [comment]
Working with the team, I arranged the nav bar and the "recently generated favicons" sections to the hero section of the landing page.
This can be seen here: https://www.figma.com/file/Om0i0dm6XOQN27utcHw5QD/Team-68_Conficon?node-id=2956%3A5550

**Comment by nwokomacj** [comment]
It was a wonderful experience working with this team. I worked closely with the team and designing the lofi and wireframe
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=2960%3A5300

**Comment by joanamadasun** [comment]
I worked with the team and commented on the button size  and allignment of the generate input. I also provided the cloud icon used 

https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=2986%3A6789
