### ISSUE TITLE
UX Research

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#122]
Series of research were carried out in the making of the website, to make life easier and better for our users

**Comment by Sinonaif** [comment]
I interviewed a few persons on the subject in view (favicons) and the results that were compiled helped the team brainstorm and get the features list

**Comment by nwokomacj** [comment]
I submitted the responses from the persons that I interviewed in the subject to the team for collective brainstorming during the course of the research.

**Comment by thatsamedolapo** [comment]
Responses I got from the interview which I carried out was taken note of and then brainstorming began. We all contributed equally

**Comment by Macdonald37** [comment]
I got to understand users needs from the interview I carried out, and the responses were vital in the whole team's brainstorming process and creation of  our user stories and website features.

**Comment by neniio** [comment]
I sent out screener questions to few surposed audience. And I got my main audience. I had an interview with them and submitted their responses which were very vital to the project. Relevant pain points and behaviours were noted.

**Comment by Adevikthur** [comment]
I worked with the team on 

- [User Persona](https://www.figma.com/file/Om0i0dm6XOQN27utcHw5QD/Team-68_Conficon?node-id=1723%3A2427)
- [User Story](https://www.figma.com/file/Om0i0dm6XOQN27utcHw5QD/Team-68_Conficon?node-id=1723%3A2461)
- [Empathy Map](https://www.figma.com/file/Om0i0dm6XOQN27utcHw5QD/Team-68_Conficon?node-id=1723%3A2383)
- [Pain Points](https://www.figma.com/file/Om0i0dm6XOQN27utcHw5QD/Team-68_Conficon?node-id=1723%3A2310)

Here's a link to the frame

**Comment by joanamadasun** [comment]
i created research question Section 4 in the interview script, and worked with my team mates on the UX research [https://docs.google.com/document/d/14mBeRUoBKj3ynNwAG_E2vqnylWgz9SolZeaH5qfoisg/edit](url)

I interviewed participant A and filled in his response. I also worked with my team mate in the creation of user personal, flow and user journey [https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=2844%3A3749](url)

**Comment by Macdonald37** [comment]
I worked on the empathy map and brainstormed ideas with my team
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=1723%3A2383
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=1723%3A2310
