### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#124]

**Comment by Sinonaif** [comment]
I made a few corrections to the already created wireframes

**Comment by thatsamedolapo** [comment]
I worked on the wireframe of some screens of the desktop view I.e some part of the landing page,login,sign up page. Team mates all contributed respective parts.

**Comment by Larhra** [comment]
I worked on the wireframe Desktop and Mobile Screens with member (Samuel) but few changes was made by the team head (Sinon).

**Comment by neniio** [comment]
I assisted in working on the wireframe of the login and sign up pages. Other tram mates did their parts respectively.

**Comment by asamstudios** [comment]
I worked with @Larhra, since I needed her wireframes as a guide for low-fi screens, I made little adjustments to the spacing system on the wireframe.

**Comment by Macdonald37** [comment]
I worked alongside my teammates on some of the wireframes

https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=2954%3A6131
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=2954%3A4633
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=2954%3A4800

**Comment by nwokomacj** [comment]
I worked on the wireframe of the following, both desktop and mobile views
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A10212
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11290
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11124
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11124
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11094
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11066
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A10986

**Comment by nwokomacj** [comment]
Wireframes did on mobile view
https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=2954%3A5261
https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=2954%3A5467
