### ISSUE TITLE
authentication page

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#127]
login and sign up pages for both desktop and mobile screens

**Comment by Sinonaif** [comment]
I supported in the creation of the sign up and login pages by bringing the template for the  and making minute edits to the already created page

**Comment by thatsamedolapo** [comment]
I helped in giving suggestion on how we are to put all the details down putting into consideration our style guide and spacing system.

**Comment by neniio** [comment]
I created the desktop login and signup page, shared ideas on how to make the the sign up and login page should look like.

**Comment by joanamadasun** [comment]
I edited the login and sign up pages by changing the input fields and adjusting the button heights. Also placing making sure the button icons and texts are alligned [https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=2963%3A6185](url)

[https://www.figma.com/file/Pb3wFzD1f7g1K4B0x9WIn7/Team-68_Conficon-(Copy)?node-id=2963%3A6256](url)
