### ISSUE TITLE
Presentation and documentation

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#129]
contributed to the slides pages and the projects documentation

**Comment by nwokomacj** [comment]
I worked with other teammates to achieve our aim towards the presentation and documentation

**Comment by thatsamedolapo** [comment]
I worked on the beginning of the documentation and my team mates helped in completing the rest.
For the presentation I and my other team mate made a video but we decided to go for the one that was much better putting into consideration all necessary things.

**Comment by Macdonald37** [comment]
I participated actively in the presentation process whilst my team members worked on the documentation.

**Comment by neniio** [comment]
I shared ideas during the preparation of the document. I assisted other team members in preparing the presentation slides.

**Comment by joanamadasun** [comment]
I wrote the introductory paragraph of the documentation and the content under sub-header "Style guide and ‘Project Conficon Design System’ " [https://docs.google.com/document/d/1NHwGURyTuiTAt0hmV3LlThZmMjWY6PStkSYUXEhmAvM/edit](url)

I also edited the general documentation with assistance from @Sinonaif. I worked with @Sinonaif to complete the presentation slides by providing images for the slides.

**Comment by asamstudios** [comment]
I was not able to contribute to this at the time, a network problem

**Comment by nwokomacj** [comment]
I worked and added input to structure properly the : Problem Statement, Research Objectives
https://docs.google.com/document/d/14mBeRUoBKj3ynNwAG_E2vqnylWgz9SolZeaH5qfoisg/edit?usp=sharing

**Comment by Conradgabe** [comment]
with @Sinonaif,  I helped curate and edit the slides content
