### ISSUE TITLE
Arranging the workspace

### ISSUE THREAD

**Issue by Jay-davisphem** [zuri-training/Favicon_gen-Team-68#13]
Arranging the Figma board and properly naming all the frames with mobile and desktop views in mind

Note: dont forget to use the style guide and observe the 4 point system

submission date: 12pm friday (7/29/2022)

**Comment by Sinonaif** [comment]
I joined in the arrangement and restructuring of the workspace for an organised and unobstructed  view for team members and visitors

**Comment by neniio** [comment]
I segmented the workspace into developers section, research section and designers section. For easy and swift navigation.

**Comment by joanamadasun** [comment]
I named frames and arranged the workspace too
