### ISSUE TITLE
low fidelity

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#132]

**Comment by Sinonaif** [comment]
I made some screens low fi after some changes were made to the high fidelity designs and i corrected some mistakes team members made in the low fidelity screens assigned to them

**Comment by nwokomacj** [comment]
I worked on lofi screens of both the desktop and mobile with other team members putting into considerations our spacing system

**Comment by thatsamedolapo** [comment]
I worked on the low fi screens together with team mates .We ensured we took into consideration the necessary steps and made use of our style guide.

**Comment by Macdonald37** [comment]
I worked on the mobile and desktop screens of the low fidelity pages alongside my teammates sticking strictly to the style guides

**Comment by Larhra** [comment]
I worked on both Desktop Mobile Screens (Low Fidelity) pages

**Comment by joanamadasun** [comment]
I edited some low fidelity screens by changing the colours used in order to create a higher contrast easier on the eyes

**Comment by neniio** [comment]
I worked on some screens of the low fidelity designs with other team mates.

**Comment by asamstudios** [comment]
I created low-fi screens for the desktop view (Hero section, Sign up, Sign in, Download page, footer section, How to use Favicon) screens

**Comment by nwokomacj** [comment]
I worked on the following lofi
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A10093
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A10434
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A12044
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A12223
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A10156
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11279
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11176
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11111
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11083
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11051
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11016
https://www.figma.com/file/EnqjiRGZlseh7DiQTQJl9V/Untitled?node-id=339%3A11014
