### ISSUE TITLE
Dropdown menu/ sidebar

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#133]

**Comment by nwokomacj** [comment]
I assisted a team member on working on the drop-down button and explaining 'absolute postion'  and usage on auto layout

**Comment by joanamadasun** [comment]
I adjusted the design and changed the labels and list area to component then edited the design by removing the edit profile button left on top and placed it in the list area with. I switched the icons used to the ones we have present in our design system.

**Comment by asamstudios** [comment]
I made contributions/suggestions to the dropdown menu and designed one, which other team members later modified.

**Comment by Adevikthur** [comment]
I designed the dropdown menu making it a modal when the prototyping is opened.

https://www.figma.com/file/Om0i0dm6XOQN27utcHw5QD/Team-68_Conficon?node-id=2960%3A6526
