### ISSUE TITLE
Recently generated favicon page

### ISSUE THREAD

**Issue by Jay-davisphem** [zuri-training/Favicon_gen-Team-68#14]
Recently generated favicon page both desktop and mobile views

Note: dont forget to use the style guide and observe the 4 point system

submission date: 6pm friday (7/29/2022)

**Comment by asamstudios** [comment]
I worked with @Adevikthur on this, we both designed different layouts/samples, I designed a mobile view for them but had issues syncing it with the file

**Comment by Adevikthur** [comment]
I worked with @asamstudios to design the web view of the recently generated favicon page.
