### ISSUE TITLE
Generate favicons from text page

### ISSUE THREAD

**Issue by Jay-davisphem** [zuri-training/Favicon_gen-Team-68#15]
Mobile view for Landing page 2 (generate from text page)

Note: dont forget to use the style guide and observe the 4 point system

submission date: 3pm friday (7/29/2022)

**Comment by nwokomacj** [comment]
The spacing system, margin and the style was cautiously implemented to design the mobile view of the landing page

**Comment by Macdonald37** [comment]
I worked on the mobile view of the landing page whilst adhering strictly to the style guides created.

**Comment by Sinonaif** [comment]
I redesigned this page after @nwokomacj worked on initially to fit to our colour background

**Comment by nwokomacj** [comment]
I designed the task assigned to me. However, the team lead contributed to make it fit to the background color
https://www.figma.com/file/vxxeG9DebSxJc05LIs9oeu/Team-68_Conficon-draft?node-id=2956%3A10900
