### ISSUE TITLE
Download favicon modal

### ISSUE THREAD

**Issue by Jay-davisphem** [zuri-training/Favicon_gen-Team-68#18]
create  mobile view for download favicon size page

Note: dont forget to use the style guide and observe the 4 point system

submission date: 3pm friday (7/29/2022)

**Comment by Sinonaif** [comment]
Personally worked on the desktop download favicon modal, and my colleague worked on the mobile screen

**Comment by neniio** [comment]
I worked on the mobile screen of the download favicon modal. Whilst my team lead worked on the desktop screen.
