### ISSUE TITLE
contact templates and styles

### ISSUE THREAD

**Issue by Jay-davisphem** [zuri-training/Favicon_gen-Team-68#98]

**Comment by Youngmaurizz** [comment]
I did the following:
1. Create a "contact.html" file inside the template folder
2. Create an external css file with the name "contact.css"
3. Create a view inside the view.py file
4. Create a url in the urls.py

**Comment by Youngmaurizz** [comment]
I did the following:

Create a "contact.html" file inside the template folder
Create an external css file with the name "contact.css"
